apiVersion: v1
kind: PersistentVolume
metadata:
  name: wordpress-pv-local-mariadb
  labels:
    type: local
spec:
  capacity:
    storage: 8Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/jixiangxv/k8s_data/wordpress"
