apiVersion: v1
kind: PersistentVolume
metadata:
  name: wordpress-pv-local
  labels:
    type: local
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/jixiangxv/k8s_data/wordpress"
